travis:
  secure:
    BINSTAR_TOKEN: Y19GsIML2DPUJrVY65kMCUgFyvGlQFCmCXOVqOJLKOpEqCR7kYadvzmVsNfjLlKg3MkF71kikyYsSNh4jHdwmyDieCn97kUNUo8xsOVw2g9SisbUVb69p/hsb0NtwC4O5uePUOnlN/c3Fi2+cOYR0xQiVxqPm3dhOsNxcPlev1bNZ7RCOwIPylsjQwE3Sd5Kke7OKdQ1lBGlRGGhkbWKMzBAH0am9JwEtP4R4ZXJjURJXhrXimQuvws08kdzn4E/1k9qkkXRWYbd0GbXECNPVt9AqUdP0d+1xXvqdjm8nw23ZnUigpjPsaKMLWFJF/yF8yvoShS6GAjdl38xwfH3H00QIDMIF9Fftd8tiHUFyzyqXyfaVgMqU6tcYfHqozv3Rc/BtyUgqA0ARad7VELhh1eY2OBf8HulXQMH+DjSgpyvG/a2XVMKg9DiRXDR/XAQC1tb1CchdMY76Rk1x5ytdP6pvRYIDs3oKbyEbs/olQKJ2nQ7GLiLfvBnsUElLX18reCaDcnINNNjQOc8zmkqUnT6KRBeskHLgmTm7vPEThU5puonBs7FMn1xLr7odV8Rg6T4tRzWnqGQ8STUOy60Y5Mqc4uVkg8oTwVKopI4QGKGTqqw53D4Qm9VigxTxJ9VDdaaWKqeximZsGsYYbQ8h/8afinDLK6V7Kw0AsERDEI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
